version: '3.7'

services:
  mongodb:
    image: mongo:5.0
    container_name: tb-mongodb # when running in docker, dbServer in packages/server/src/configs/server.config.json
    ports:
      - 27017:27017

  redis:
    image: bitnami/redis:6.0
    container_name: tb-redis
    ports:
      - 6379:6379 # for redis server from redisPort
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build: .
    container_name: typescript-boilerplate
    working_dir: /typescript-boilerplate
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/typescript-boilerplate
      - ./.cache:/usr/local/share/.cache/
    entrypoint: /bin/bash
    ports:
      - 8080:8080 # for @vue/cli
      - 8000:8000 # for client
      - 3000:3000 # for server
      - 8712:8712 # for server when NODE_ENV != development
      - 9001:9001 # for user service
